CREATE TABLE [dbo].[Appointments]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[StartAt] DATETIME2 NOT NULL,
	[EndAt] DATETIME2 NOT NULL,
	[Accepted] BIT NOT NULL DEFAULT 0,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_Appointments_User] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
