CREATE TABLE [dbo].[Schedules]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Title] NVARCHAR(100) NULL,
	[Details] TEXT NULL,
	[StartsAt] DATETIME2 NOT NULL,
	[EndsAt] DATETIME2 NOT NULL,
	[ModuleId] INT NOT NULL,
	CONSTRAINT [FK_Schedules_Module] FOREIGN KEY ([ModuleId]) REFERENCES [Modules]([Id])
)
