CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Email] NVARCHAR(320) NOT NULL, 
    [NormalizedEmail] NVARCHAR(320) NOT NULL,
    [PasswordHash] BINARY(32) NOT NULL, 
    [Salt] UNIQUEIDENTIFIER NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL, 
    [Lastname] NVARCHAR(100) NOT NULL,
    [ProfilePicture] NVARCHAR(255) NOT NULL, 
    [BirthDate] DATE NOT NULL, 
    [ConcurrencyStamp] UNIQUEIDENTIFIER NOT NULL, 
    [SecurityStamp] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL, 
    [UpdatedAt] DATETIME2 NULL, 
    [DeletedAt] DATETIME2 NULL
)
