CREATE TABLE [dbo].[UsersTokens]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Type] NVARCHAR(100) NOT NULL,
	[Value] NVARCHAR(64) NOT NULL,
	[DeliveryDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[ExpirationDate] DATETIME2 NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_UsersTokens_User] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
